export const FrontEndRoutes = {
  Dashboard: '/dashboard',
  Home: '/',
  Login: '/login',
  SignUp: '/signup',
  CompanySignUp: '/signup/company',
  SponsorSignUp: '/signup/sponsor',
  AttendeeSignUp: '/signup/attendee',
  EventOrganizerSignUp: '/signup/eventOrganizer',
  CreateCompanyUser: '/signup/company-user',
  Events: '/events',
  EventDetails: '/event/:id/details',
  Schedule: '/schedule',
  Community: '/community',
  Discussion: '/community/discussion',
  Analytics: '/analytics',
  Messages: '/messages',
  Notifications: '/notifications',
  Support: '/support',
  Profile: '/profile',
  EventRegistration: '/event/event-details/register',
  EventStreaming: '/event/event-details/streaming',
} as const;
