export const FrontEndRoutes = {
  Dashboard: '/dashboard',
  Home: '/',
  Login: '/login',
  SignUp: '/signup',
  CompanySignUp: '/signup/company',
  AttendeeSignUp: '/signup/attendee',
  CreateCompanyUser: '/signup/company-user',
  Events: '/events',
  Event: {
    base: '/event',
    param: ':id',
    definition: '/event/:id',
  },
  Schedule: '/schedule',
  Community: '/community',
  Discussion: '/community/discussion',
  Analytics: '/analytics',
  Messages: '/messages',
  Notifications: '/notifications',
  Support: '/support',
  Profile: '/profile',
  EventDetails: '/event/event-details',
  EventRegistration: '/event/event-details/register',
  EventStreaming: '/event/event-details/streaming',
} as const;
