export const FrontEndRoutes = {
  Dashboard: '/dashboard',
  Home: '/',
  Login: '/login',
  SignUp: '/signup',
  CompanySignUp: '/signup/company',
  SponsorSignUp: '/signup/sponsor',
  AttendeeSignUp: '/signup/attendee',
  EventOrganizerSignUp: '/signup/eventOrganizer',
  CreateCompanyUser: '/signup/company-user',
  Events: '/events',
  
  Schedule: '/schedule',
  Community: '/community',
  Discussion: '/community/discussion',
  Analytics: '/analytics',
  Messages: '/messages',
  Notifications: '/notifications',
  Support: '/support',
  Profile: '/profile',
  EditProfile: '/profile/edit',
  EventRegistration: '/event/:id/register',
  EventDetails: '/event/:id/details',
  EventStreaming: '/event/:id/streaming',
  EventViewer: '/event/:id/viewer',
  EventConfirmation: '/event/:id/confirmation',
} as const;
